
#ifndef SimpleBank_CONFIG_h
#define SimpleBank_CONFIG_h

/*CONFIGURATIONS*/
#define DEFAULT_MANAGER "3307"
#define DEFAULT_MAINTENANCE "mgr"
#define DEFAULT_PASSWORD "pass"
#define DEFAULT_CREDIT_LIMIT 2000

/*SYSTEM CONSTANTS, DO NOT MODIFY*/
#define PAY_MIN_10 0
#define PAY_FULL 1
#define HIDE_TRANSACTIONS_OFF 0
#define HIDE_TRANSACTIONS_ON 1

#endif
